channels:
    - pytorch
    - nvidia
    - conda-forge
name:
    torch-em
dependencies:
    - affogato
    - bioimageio.core >=0.5.0
    - python-elf
    - pytorch-cuda=11.6  # you may need to update the pytorch version to match your system
    - tensorboard
    - tifffile
    - torchvision
    - tqdm
    - kornia
